### ISSUE TITLE
有测试page的方法吗

### ISSUE THREAD

**Issue by hopperhuang** [wechat-miniprogram/j-component#1]
请问有测试页面逻辑的方法吗？ 这个库可以用作component的测试已经很赞了，可是我还想要一个测试page的方法，请问有吗？

**Comment by JuneAndGreen** [comment]
页面其实也可以理解为一个自定义组件，可以通过 Component 构造器来构造页面，[官方文档戳这里](https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/component.html#%E4%BD%BF%E7%94%A8-component-%E6%9E%84%E9%80%A0%E5%99%A8%E6%9E%84%E9%80%A0%E9%A1%B5%E9%9D%A2)，所以理论上这个也能用来测页面。

**Comment by hopperhuang** [comment]
借贵宝地问一下，this.data属性和this.__data__属性，和this.__viewData__属性三者之间有什么区别和关联吗？

**Comment by JuneAndGreen** [comment]
@hopperhuang 这个请到开发者社区提问，理论上来说并不建议去使用 __ 开头的这几个属性，这是内部使用的，后续会有变更的可能。
