### ISSUE TITLE
关于自定义组件实现的疑问

### ISSUE THREAD

**Issue by zhangking** [wechat-miniprogram/j-component#13]
hi 你好，我有个疑问，希望你帮帮我看看。
关于自定义组件，因为组件系统是在渲染层实现，但是原则上用户的逻辑代码在逻辑层执行，我比较疑惑的是自定义组件是如何实现的，即自定义组件在哪一层实例化，如何通信？

**Comment by JuneAndGreen** [comment]
关于小程序的原理，其实更推荐你去微信开放社区去咨询。

回到正题：自定义组件的设计其实有点复杂，在渲染层和逻辑层都会有实例，两者实例相似但不完全相同，渲染层会真正调 dom 接口拼出 dom 树，逻辑层则会嵌入用户的 js 代码。两边会通过一个叫同步位的机制来确保两边树结构同步，包括初创时的同步和 setData 更新时的同步，以及事件的反馈。
