### ISSUE TITLE
generate virtualnode 时希望给for语句添加一个默认空数组

### ISSUE THREAD

**Issue by Blackgan3** [wechat-miniprogram/j-component#14]
### 背景

在使用小程序运行时增强框架时，框架会提供computed watch等语法，这些语法糖是在组件attached生命周期注入相应的mixin实现，在第一次jComponent.create执行时，相应的data对象中并不存在wx:for所取数据，会在执行list.length时报错，所以希望这里加一个默认空数组的兜底逻辑。

### 具体改动
我尝试给项目提pr，但并无项目权限，具体改动在 src/template/virtualnode.js 207行

```js
        const list = expr.calcExpression(statement.for, data) 
        // 修改为
        const list = expr.calcExpression(statement.for, data) || []
```

辛苦review支持

**Comment by JuneAndGreen** [comment]
已补充到：j-component@1.4.5 版本

**Comment by Blackgan3** [comment]
OK， 感谢
