### ISSUE TITLE
`create` 方法如何渲染默认 slot?

### ISSUE THREAD

**Issue by SevenOutman** [wechat-miniprogram/j-component#16]
如题，例如我需要测试一个类 button 组件，我需要渲染其文字内容，形如：

```js
create(button, {
  children: 'Button Text'
})
```

现在的 `create` 方法（以及 `miniprogram-simulate` 的 `render` 方法）似乎并不支持

**Comment by JuneAndGreen** [comment]
小程序目前应该还没有支持默认 slot 功能，j-component 是用的和小程序一套的组件系统，所以暂时无法支持这种能力。对于 slot 的测试，建议是创建一个父级组件，用这个父级组件来引用你要测试的组件，传入 slot 来达到测试效果。
