### ISSUE TITLE
不支持模拟小程序的picker-view-column组件吗

### ISSUE THREAD

**Issue by Andylis** [wechat-miniprogram/j-component#17]
不支持模拟小程序的picker-view-column组件吗

**Comment by JuneAndGreen** [comment]
j-component 不提供内置组件的具体实现， j-compoenent 主要服务于 miniprogram-simulate，提供一套组件系统用于做第三方自定义组件的逻辑测试，因为对于开发者来说内置组件本身就是黑盒，所以这里内置组件的实现就是一个壳。如果开发者有需要的话可以按需模拟出用于测试的接口来的，直接覆盖掉内置组件的那个壳就行。

**Comment by JuneAndGreen** [comment]
<img width="390" alt="image" src="https://user-images.githubusercontent.com/7931744/177461836-6d89ec20-c552-4f66-92af-680aef6b4f06.png">

这是测试用例里 view 的注册方式，可覆盖注册，以供参考
