### ISSUE TITLE
npm 上的源码与github上的源码并不一致

### ISSUE THREAD

**Issue by hopperhuang** [wechat-miniprogram/j-component#2]
为什么不同步更新呢

**Comment by JuneAndGreen** [comment]
已将近期更新发布到 0.0.2 版本上来。

这个一开始是作为脚手架 [miniprogram-custom-component](https://github.com/wechat-miniprogram/miniprogram-custom-component) 的测试框架来开发的，因为目前只完成了基础功能，所以发版比较少，在脚手架那边是直接通过 github 仓库地址的方式来引入依赖的。
