### ISSUE TITLE
bug: component.setdata方法的实现与小程序的component.setdata行为不一致

### ISSUE THREAD

**Issue by hopperhuang** [wechat-miniprogram/j-component#3]
github地址：https://github.com/hopperhuang/miniprogram-reactive
这是我自己写的一个用于小程序的computed和watch，类似于vue的实现，通过监听this.data属性的getter和setter来实现的。
单元测试,initcomponent是报错的,component.setdata的时候，并没有触发this.data的setter,所以computed和watch并没有触发。
我的代码在小程序的开发工具上跑是没有问题的，具体的例子在examples/miniprogram里面，可以跑起来看看效果

**Comment by hopperhuang** [comment]
如果确定是有问题的话，希望此问题可以修复，否则作为单元测试的基本框架来用也有点美中不足了，谢谢。

**Comment by JuneAndGreen** [comment]
j-component 的实现和原本小程序的实现可以说是完全不一样的，因为两者的环境差距很大。这里的问题不是 setData 的问题，而是没有特殊处理覆写 data 字段的做法。 j-component 的 0.0.3 给兼容了。

**Comment by hopperhuang** [comment]
后续有打算出一套测试框架吗，比如把testhelper封装成一个NPM包暴露接口这样子。

**Comment by JuneAndGreen** [comment]
目前测试相关是集成到这里了：https://github.com/wechat-miniprogram/miniprogram-custom-component
