### ISSUE TITLE
Feature: 外链wxs的支持

### ISSUE THREAD

**Issue by Pasoul** [wechat-miniprogram/j-component#5]
目前我的做法是正则匹配到带有src的wxs标签，用读取到外链文件内容后，replace掉原来的wxs标签内容：

替换前：
```
<wxs src="../../common/wxs/array.wxs" module="utils" />
<view>{{utils.xxx}}</view>
```
替换后：
```
<wxs module="utils" />
// 这里是common/wxs/array.wxs文件内容
</wxs>
<view>{{utils.xxx}}</view>
```

这样做效率挺低的，基本上每个文件都是外链wxs，都需要替换一下，作者有更好的思路吗？

**Comment by JuneAndGreen** [comment]
如果不需要在 web 环境进行模板编译的话，可以考虑使用官方编译器（二进制）来进行编译，具体可以参考自定义组件测试工具 miniprogram-simulate。

**Comment by JuneAndGreen** [comment]
使用官方编译器可参考 demo：https://github.com/wechat-miniprogram/miniprogram-simulate/tree/master/test/comp7
