### ISSUE TITLE
更新到1.1.2之后，props传值报错。

### ISSUE THREAD

**Issue by rubbishquan** [wechat-miniprogram/j-component#6]
而且querySelector也取不到实例啦。

` console.error node_modules/miniprogram-exparser/exparser.min.js:1
      TypeError: Cannot read property 'parentNode' of undefined
`

**Comment by rubbishquan** [comment]
`else if (isComponentNode && exparser.Component.hasPublicProperty(exparserNode, name)) {
      // public 属性，延迟处理
      dataProxy.scheduleReplace([name], value);
      needDoUpdate = true;
    }`

目测是scheduleReplace这方法出问题了，但是miniprogram-exparser没开源并且做了压缩，搞不动了。

**Comment by rubbishquan** [comment]
不知道这里的public属性指的是什么意思，字符串、布尔值和对象都能走到这个判断里。
是不是带有observer函数的属性就是public属性？

**Comment by rubbishquan** [comment]
求求快修，现在更新后测试套件全挂了。

**Comment by JuneAndGreen** [comment]
刚刚修了官方编译器的一个小问题，看看更新一下 miniprogram-simulate 到最新版本看看。如果还不行麻烦提供一下能复现问题的 demo。

**Comment by rubbishquan** [comment]
修复了感谢大佬！observer里的String的更新也解决了。
